### ISSUE TITLE
Streamable processing (both input & output need to be streams)

### ISSUE THREAD

**Issue by paulofaria** [Zewo/gzip#4]

**Comment by czechboy0** [comment]
Braindump: currently the data is gzip handle is opened and then in a while loop the passed-in data is encoded/decoded in chunks. We need to rewrite things to take a sequence, which will return the next chunk (input stream) and we encode/decode that chunk into the output stream. This way it can be plugged into the full pipeline easily. Then, the APIs that actually take the full (NS)Data can be built on top of it by just opening an output stream and doing everything in one while loop, returning the full processed data at the end.

Fortunately the zlib API is made for this sort of thing, so it should be a matter of tens of minutes to rewrite this.

**Comment by czechboy0** [comment]
WIP: https://github.com/Zewo/gzip/compare/master...hd/streams
